/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;

public class Agenda {
    private ArrayList<Contato> contatos;

    public Agenda(ArrayList<Contato> contatos) {
        this.contatos = contatos;
    }

    public boolean addContato(Contato contato) {
        return this.contatos.add(contato);
    }

    public boolean removeContato(int index) {
        try {
            this.contatos.remove(index);
            return true;
        }catch (Exception e){
            return false;
        }
    }

    public boolean addTelefone(int index, Telefone telefone) {
        return this.contatos.get(index).AddTelefone(telefone);
    }

    public boolean addEmail(int index, Email email) {
        return this.contatos.get(index).AddEmail(email);
    }

    public boolean updateTelefone(int index, int telIndex, Telefone telefone) {
        try {
            return this.contatos.get(index).updateTelefone(telIndex, telefone);
        }catch (Exception e){
            return false;
        }
    }

    public boolean updateEmail(int index, int emailIndex, Email email) {
        return this.contatos.get(index).updateEmail(emailIndex, email);
    }

    public boolean removeTelefone(int index, int telIndex) {
        try {
            return this.contatos.get(index).removeTelefone(telIndex);
        }catch (Exception e){
            return false;
        }
    }

    public boolean removeEmail(int index, int emailIndex) {
        try {
            return this.contatos.get(index).removeEmail(emailIndex);
        }catch (Exception e){
            return false;
        }
    }

    public Contato getContato(int index){
        return this.contatos.get(index);
    }

    public boolean updateContato(int index, Contato contato){
        this.contatos.set(index, contato);
        return true;
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();

        for(int i = 0; i < this.contatos.size(); i++){
            sb.append("\n");
            sb.append(i);
            sb.append(" - ");
            sb.append("[");
            sb.append(this.contatos.get(i));
            sb.append("\n\t]");
            if(i != this.contatos.size() -1){
                sb.append(", ");
            }
        }

        return sb.toString();
    }

}
