/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

public class Contato {
    private String nome;
    private String sobrenome;
    private LocalDate dataNasc;
    private ArrayList<Telefone> telefones;
    private ArrayList<Email> emails;

    public Contato(String nome, String sobrenome, LocalDate dataNasc, ArrayList<Telefone> telefones, ArrayList<Email> emails){
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.dataNasc = dataNasc;
        this.telefones = telefones;
        this.emails = emails;
    }

    public boolean AddTelefone(Telefone telefone){
        return this.telefones.add(telefone);
    }

    public boolean AddEmail(Email email){
        return this.emails.add(email);
    }

    public boolean removeTelefone(int index){
        this.telefones.remove(index);
        return true;
    }

    public boolean removeEmail(int index){
        this.emails.remove(index);
        return true;
    }

    public boolean updateTelefone(int index, Telefone telefone){
        this.telefones.set(index, telefone);
        return true;
    }

    public boolean updateEmail(int index, Email email){
        this.emails.set(index, email);
        return true;
    }

    public String toString(){
        return String.format("\n\t nome: %s,\n\t sobrenome: %s,\n\t data de nascimento: %s,\n\t telefones: %s,\n\t emails: %s", this.nome, this.sobrenome, dataNasc.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")), formatArrayListToString(this.telefones), formatArrayListToString(this.emails));
    }

    private String formatArrayListToString(ArrayList<?> arrayList){
        StringBuilder sb = new StringBuilder();
        sb.append("(");
        for (int i = 0; i < arrayList.size(); i++) {
            sb.append("\n\t\t ");
            sb.append(i);
            sb.append(" - ");
            sb.append(arrayList.get(i));
            if(i != arrayList.size() - 1){
                sb.append(", ");
            }
        }
        sb.append("\n\t )");
        return sb.toString();
    }



}
