/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class Email {
    private String rotulo;
    private String valor;

    public Email(String rotulo, String valor) {
        if (isValidEmail(valor)) {
            this.rotulo = rotulo;
            this.valor = valor;
        } else {
            throw new IllegalArgumentException("Email inválido");
        }
    }

    private boolean isValidEmail(String valor) {
        String emailRegexValidator = "^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$";
        return valor.matches(emailRegexValidator);
    }

    public String toString() {
        return String.format("%s: %s", rotulo, valor);
    }
}
