/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.function.Function;

public class App {

    public static void main(String[] args) {
        HashMap<String, Livro> banco = new HashMap<>();

        ArrayList<Autor> autoresH = new ArrayList<>();
        autoresH.add(new Autor("J. K. Rowling", "britânica"));
        Livro harryPotter = new Livro("Harry Potter", 20.00, autoresH, "0000000000001");

        banco.put(harryPotter.getIsbn(), harryPotter);

        ArrayList<Autor> autoresP = new ArrayList<>();
        autoresP.add(new Autor("Rick Riordan", "americano"));

        Livro percyJackson = new Livro("Percy Jackson", 25.00, autoresP, "000000000002");

        banco.put(percyJackson.getIsbn(), percyJackson);
        System.out.println(banco);






    }
}
