/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Bola bola = new Bola("Basquete", 10, 3, "Vermelha");
        Bola bola2 = new Bola("Basquete", 10, 3, "Vermelha");
        if(bola.equals(bola2)){
            System.out.println("Bolas iguais");
        }
    }
}
