/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.time.LocalDate;
import java.util.ArrayList;

public class App {
    private ArrayList<Tarefa> tarefas;

    public App(){
        this.tarefas = new ArrayList<>();
    }

    public static void main(String[] args) {
        App app = new App();
        Pessoa pessoas = new Pessoa("Márcio", "a@a.com");
        Categoria categoria = new Categoria("1","Tarefa de programação");
        Tarefa tarefa = new Tarefa("Tarefa 1", LocalDate.of(2024, 02, 07), categoria);
        tarefa.setResponsavel(pessoas);
        tarefa.setResponsavel(pessoas);
        app.tarefas.add(tarefa);
        System.out.println(app.tarefas);
    }
}
