/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;

public class App {
    private ArrayList<Veiculo> garagem = new ArrayList<Veiculo>();
    public static void main(String[] args) {
    }
}
