/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Ponto ponto = new Ponto("vermelho", 1, 1);
        Linha linha = new Linha("vermelho", ponto, new Ponto("vermelho", 5, 1));
        System.out.println(linha.desenhar());
    }
}
