/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Ponto pontoA = new Ponto(10, 1);
        Ponto pontoB = new Ponto(5, 10);

        System.out.println(pontoA);
        System.out.println(pontoB);
        System.out.println("A distância entre A e B é: " + pontoA.distancia(pontoB));
    }
}
