/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Car car = new Car(200);
        System.out.println(car.getCurrentSpeed());

    };
}
