/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.Random;

public class BuzzLightyear {
    private boolean helmetOpened = false;
    private boolean wingsOpened = false;

    private String[] phrases = {
            "Isto não é voar. Isto é cair, com estilo!",
            "Ao infinito e além!",
            "Nunca duvidei de mim mesmo, Comandante, e não vou começar agora!",
            "Embora você tenha tentado acabar comigo, a vingança não é um ideal que promovemos no meu planeta.",
            "Eu sou Buzz Lightyear!",
            "Comando Estelar pronto pra voar!"};

    public boolean isHelmetOpened(){
        return helmetOpened;
    }

    public boolean isWingsOpened(){
        return wingsOpened;
    }

    public boolean changeHelmetState(){
        helmetOpened = !helmetOpened;
        return helmetOpened;
    }

    public boolean changeWingsState(){
        wingsOpened = !wingsOpened;
        return wingsOpened;
    }

    public String armAttack(){
        return "Golpeando com braço articulado...";
    }

    public String laserAttack(){
        return "Disparando Laser...";
    }

    public String getPhrase(){
        Random r = new Random();
        int phrasePosition = r.nextInt(6);
        return phrases[phrasePosition];
    }


}
