/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;


public class Pen {
    private String color;
    private int capacity;


    public Pen(String color, int capacity) {
        this.color = color;
        this.capacity = capacity;
    }

    public Pen(String color) {
        this(color, 100);
    }

    public Pen() {
        this("Vermelha", 100);
    }

    public String drawing(){
        if(capacity == 0){
            return "Impossível desenhar, caneta está sem tinta.";
        }
        capacity--;
        return "Desenhando com a cor " + color + "...";
    }

    public void setColor(String color){
        this.color = color;
    }

    public int getCapacity(){
        return capacity;
    }

}
